### PR TITLE
Adding Database (path / and /data in the URL) & paving the way for SSM for doing Failure injection

### PR DESCRIPTION
**Pull request by adhorn**
DEPENDS ON https://github.com/setheliot/aws-well-architected-labs/pull/34
Please merge it before.

* Addressing Issues #27 #17 #18

- Adding Database write and read on path / an /data
- Adding role to enable run command on the ec2 instances with tag:SSMTage:chaos-ready

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by setheliot** [comment]
Adrian, is this PR a stand-alone change to enable Injecting Chaos using SSM?  We still need to upload the [SSM documents](https://github.com/adhorn/chaos-ssm-documents).  Will we have students do that as part of the lab?  Looks like you plan to have it part of the setup since you added the `Chaos-SSM` policy to the `WebAppLambdaRole`
	
Also, super-convenient that `AmazonEC2RoleforSSM` was already part of `WebServerRole`

**Comment by setheliot** [comment]
Also should we replace `AmazonEC2RoleforSSM ` with `AmazonSSMManagedInstanceCore`?

**Comment by adhorn** [comment]
@setheliot  not a stand alone PR. It includes other stuff like the database in the webserver and new url path (/ and /data)

**Comment by adhorn** [comment]
> Also should we replace `AmazonEC2RoleforSSM ` with `AmazonSSMManagedInstanceCore`?

Not sure I understand. What do you mean? where?

**Comment by setheliot** [comment]
> > Also should we replace `AmazonEC2RoleforSSM ` with `AmazonSSMManagedInstanceCore`?
> 
> Not sure I understand. What do you mean? where?

SSM chaos injection only works when  the EC2 instances have SSM permissions.  They currently have [AmazonEC2RoleforSSM](https://github.com/setheliot/aws-well-architected-labs/blob/master/Reliability/300_Testing_for_Resiliency_of_EC2_RDS_and_S3/Code/CloudFormation/web_server_autoscaling.json#L113) which will work fine.   But as per [this it has been replaced by AmazonSSMManagedInstanceCore ](https://docs.aws.amazon.com/systems-manager/latest/userguide/auth-and-access-control-iam-identity-based-access-control.html).  I caught this because I noted it was `AmazonSSMManagedInstanceCore` you recommended using in [your blog](https://medium.com/@adhorn/injecting-chaos-to-amazon-ec2-using-amazon-system-manager-ca95ee7878f5) :-)

**Comment by setheliot** [comment]
looks good.  Tested
image

**Pull request merged**
